/**
 * The only way the rest of `src/` reaches the generated `Database` type. `database.types.ts`
 * is regenerated by `npm run db:types` and checked for freshness in CI; nothing outside
 * `src/lib/` indexes into it by hand (lint enforces the import boundary, S1.5 AC1).
 */
import type { Database } from '@/lib/database.types'

export type { Database, Json } from '@/lib/database.types'

type Public = Database['public']

export type TableName = keyof Public['Tables']
export type EnumName = keyof Public['Enums']
export type FnName = keyof Public['Functions']

export type Tables<K extends TableName> = Public['Tables'][K]['Row']
export type Insert<K extends TableName> = Public['Tables'][K]['Insert']
export type Update<K extends TableName> = Public['Tables'][K]['Update']
export type Enums<K extends EnumName> = Public['Enums'][K]
export type Fn<K extends FnName> = Public['Functions'][K]

/** One row of a set-returning RPC, e.g. `FnRow<'get_event_preview'>`. */
export type FnRow<K extends FnName> = Fn<K>['Returns'] extends (infer R)[] ? R : never
