import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

// The conventions ESLint holds up, as named groups, so that a file exempt from one group keeps
// every other. An `off` for a whole rule would lift them all; composing lists does not. Each
// group's exemptions are the `files` blocks at the bottom and nowhere else (S1.5).

/** S0.1 AC6, D35 — one formatter, src/lib/time.ts. A13 keeps the Intl ban to DateTimeFormat. */
const DATE_RULES = [
  {
    selector: 'MemberExpression[property.name=/^toLocale(String|DateString|TimeString)$/]',
    message: 'Use formatEventTime() from @/lib/time. CLAUDE.md section 3, decision D35.',
  },
  {
    selector: "NewExpression[callee.object.name='Intl'][callee.property.name='DateTimeFormat']",
    message: 'Use formatEventTime() from @/lib/time. CLAUDE.md section 3, decision D35.',
  },
]

/** S4.6 AC13, D30 — `series_id` is set by the generator and read by no query. Written the way
 *  the DateTimeFormat ban above is written, it fails any `series_id` string literal (a select,
 *  filter, eq or order argument) or property access under `src/` outside `database.types.ts`, so
 *  no read path can reference it. The row-schema mirror in schemas.ts uses it as an object key,
 *  which is a definition, not a read, and is not matched. Tests are exempt below, since a test
 *  asserting the column's absence names it on purpose. */
const SERIES_RULES = [
  {
    selector: "Literal[value='series_id']",
    message: 'No read path references series_id; the generator sets it, no query reads it. D30.',
  },
  {
    selector: "MemberExpression[property.name='series_id']",
    message: 'No read path references series_id; the generator sets it, no query reads it. D30.',
  },
]

/** S1.5 AC7, D38 — scripts/check-conventions.mjs repeats this check across the whole tree. */
const SECRET_RULES = [
  {
    selector: 'Identifier[name=/SERVICE_ROLE/]',
    message: 'The service-role key never appears in the browser bundle. Decision D38.',
  },
]

/** S1.5 AC6 — src/lib/env.ts parses the environment once; src/lib/sentry.ts reads it before
 *  env.ts can load. Tests may read it to assert what the modules under test were given. */
const ENV_RULES = [
  {
    selector:
      "MemberExpression[object.type='MetaProperty'][object.meta.name='import'][object.property.name='meta'][property.name='env']",
    message: 'Read env from @/lib/env, which validates it once at startup. S1.5 AC6.',
  },
]

/** S2.1 DoD, D19 — the auth seam. Every supabase.auth.signUp and signInWithPassword goes
 *  through src/lib/auth.ts, so the phone-vs-synthetic-email choice stays a one-file change and
 *  cannot leak. */
const AUTH_SEAM_RULES = [
  {
    selector: "CallExpression[callee.property.name='signUp']",
    message: 'Call signUpWithIdentifier from @/lib/auth, the one auth seam. S2.1 DoD, D19.',
  },
  {
    selector: "CallExpression[callee.property.name='signInWithPassword']",
    message: 'Call signInWithIdentifier from @/lib/auth, the one auth seam. S2.1 DoD, D19.',
  },
]

/** S1.5 AC15, A6 — three key factories in src/api/queryKeys.ts; no literal key, no fourth factory. */
const KEY_RULES = [
  {
    selector: "Property[key.name='queryKey'][value.type='ArrayExpression']",
    message: 'Query keys come from eventKeys, teamKeys or userKeys in @/api/queryKeys. S1.5 AC15.',
  },
  {
    selector: "Property[key.name='queryKey'] > TSAsExpression > ArrayExpression",
    message: 'Query keys come from eventKeys, teamKeys or userKeys in @/api/queryKeys. S1.5 AC15.',
  },
  {
    selector: 'ExportNamedDeclaration > VariableDeclaration > VariableDeclarator[id.name=/Keys$/]',
    message:
      'No fourth key factory. Add a member to eventKeys, teamKeys or userKeys in src/api/queryKeys.ts. A6.',
  },
]

/** S1.5 AC4 — one client, src/lib/supabase.ts. */
const CLIENT_IMPORT = {
  name: '@supabase/supabase-js',
  importNames: ['createClient'],
  message: 'Import the single client from @/lib/supabase. S1.5 AC4.',
}

/** S1.5 AC1 — the generated file is reached through the aliases in src/lib/db.ts. */
const GENERATED_TYPES_IMPORT = {
  group: ['**/database.types', '**/database.types.ts'],
  message: 'Import Database, Tables, Enums and Fn from @/lib/db, not the generated file. S1.5 AC1.',
}

const restrictedSyntax = (...groups) => ['error', ...groups.flat()]
const restrictedImports = ({
  paths = [CLIENT_IMPORT],
  patterns = [GENERATED_TYPES_IMPORT],
} = {}) => ['error', { paths, patterns }]

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      'spec',
      '.playwright',
      // Generated by `npm run db:types`; the CLI's shapes are not this project's style to fix.
      'src/lib/database.types.ts',
    ],
  },

  js.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,

  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
  },

  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat['recommended-latest'], reactRefresh.configs.vite],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      'no-restricted-syntax': restrictedSyntax(
        DATE_RULES,
        SECRET_RULES,
        ENV_RULES,
        KEY_RULES,
        AUTH_SEAM_RULES,
        SERIES_RULES,
      ),
      'no-restricted-imports': restrictedImports(),
    },
  },

  // Generated shadcn primitives export their cva variants next to the component, which is
  // the library's own shape and what every consuming story imports. Fast refresh is a dev
  // convenience; the rule is off for these files only, and nothing else is relaxed.
  {
    files: ['src/components/ui/**/*.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },

  // --- Exemptions, each one file or one kind of file, each keeping every other group. ---

  // The one formatter in the codebase is allowed to format.
  {
    files: ['src/lib/time.ts'],
    rules: {
      'no-restricted-syntax': restrictedSyntax(
        SECRET_RULES,
        ENV_RULES,
        KEY_RULES,
        AUTH_SEAM_RULES,
        SERIES_RULES,
      ),
    },
  },
  // The one parser of the environment, and the module that must initialise before it.
  {
    files: ['src/lib/env.ts', 'src/lib/sentry.ts'],
    rules: {
      'no-restricted-syntax': restrictedSyntax(
        DATE_RULES,
        SECRET_RULES,
        KEY_RULES,
        AUTH_SEAM_RULES,
        SERIES_RULES,
      ),
    },
  },
  // Tests assert what the environment handed the module under test.
  {
    files: ['src/**/__tests__/**/*.{ts,tsx}', 'src/**/*.test.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': restrictedSyntax(
        DATE_RULES,
        SECRET_RULES,
        KEY_RULES,
        AUTH_SEAM_RULES,
      ),
    },
  },
  // The one module that constructs a query key.
  {
    files: ['src/api/queryKeys.ts'],
    rules: {
      'no-restricted-syntax': restrictedSyntax(
        DATE_RULES,
        SECRET_RULES,
        ENV_RULES,
        AUTH_SEAM_RULES,
        SERIES_RULES,
      ),
    },
  },
  // The one auth seam: the only file allowed to call supabase.auth.signUp / signInWithPassword.
  {
    files: ['src/lib/auth.ts'],
    rules: {
      'no-restricted-syntax': restrictedSyntax(
        DATE_RULES,
        SECRET_RULES,
        ENV_RULES,
        KEY_RULES,
        SERIES_RULES,
      ),
    },
  },
  // The one client, and the one module that aliases the generated types.
  {
    files: ['src/lib/supabase.ts'],
    rules: { 'no-restricted-imports': restrictedImports({ paths: [] }) },
  },
  {
    files: ['src/lib/db.ts'],
    rules: { 'no-restricted-imports': restrictedImports({ patterns: [] }) },
  },

  // Plain JS tooling — eslint.config.js, scripts/*.mjs — is outside both tsconfigs, so the
  // type-aware rules have no program to consult. Lint it without them.
  {
    files: ['**/*.{js,mjs,cjs}'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: { globals: globals.node },
  },

  // vite.config.ts and vitest.config.ts run in Node, not the browser.
  {
    files: ['*.config.ts'],
    languageOptions: { globals: globals.node },
  },

  prettier,
)
