// S1.2 — two source scans the spec wants enforced by a test, not by review. Runs in the `check`
// job under the unit config; needs no database. Every scan opens the same tree, so a rule added
// later is one entry in RULES.
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { describe, expect, it } from 'vitest'

const SRC = 'src'
/** Generated by `npm run db:types`: a type declaration, not code that reads or writes anything. */
const GENERATED_TYPES = join('src', 'lib', 'database.types.ts')
const EXTS = ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.css', '.html', '.json']

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) yield* walk(full)
    else if (EXTS.some((e) => full.endsWith(e))) yield full
  }
}

interface Rule {
  name: string
  pattern: RegExp
  allow?: (path: string) => boolean
}

const RULES: Rule[] = [
  // AC4 — a number is never proof of identity. Nothing in the client reads a confirmation stamp
  // or branches on one.
  {
    name: 'reads a confirmation timestamp',
    pattern: /phone_confirmed_at|email_confirmed_at|\bconfirmed_at\b/,
  },
  // AC27 — the service-role key never enters the bundle's module graph (D38).
  { name: 'names the service-role key', pattern: /SERVICE_ROLE/ },
  // AC12 — nothing in the client assigns is_admin. A Zod field or a select of the column is
  // fine; `is_admin = …` or a literal `is_admin: true/false` is not.
  {
    name: 'assigns is_admin',
    pattern: /\bis_admin\s*(=[^=]|:\s*(true|false)\b)/,
    allow: (p) => p === GENERATED_TYPES,
  },
]

function violations(rule: Rule) {
  const hits: string[] = []
  for (const file of walk(SRC)) {
    const rel = relative('.', file)
    if (rule.allow?.(rel)) continue
    readFileSync(file, 'utf8')
      .split('\n')
      .forEach((line, i) => {
        if (rule.pattern.test(line)) hits.push(`${rel}:${String(i + 1)}  ${line.trim()}`)
      })
  }
  return hits
}

describe('nothing under src/', () => {
  it.each(RULES.map((r) => [r.name, r] as const))('%s', (_name, rule) => {
    expect(violations(rule)).toEqual([])
  })
})

describe('AC12 — the one is_admin write outside the bootstrap migration is the seed', () => {
  it('exactly one `set is_admin = true` / `update({ is_admin: true` in the repo', () => {
    const pattern = /set\s+is_admin\s*=\s*true|update\(\{\s*is_admin:\s*true/
    const self = join('tests', 'guards', 'source-scan.test.ts') // names the pattern it looks for
    const hits: string[] = []
    for (const root of ['supabase', 'tests', 'scripts', 'src']) {
      for (const file of walk(root)) {
        if (relative('.', file) === self) continue
        if (file.endsWith('.sql') || EXTS.some((e) => file.endsWith(e))) {
          if (pattern.test(readFileSync(file, 'utf8'))) hits.push(relative('.', file))
        }
      }
    }
    // When the production bootstrap migration (Q6) lands, add its path here.
    expect(hits).toEqual([join('supabase', 'seed', 'seed.ts')])
  })
})

describe('AC27 — the key never carries a VITE_ prefix', () => {
  it.each([
    '.env.example',
    join('.github', 'workflows', 'deploy.yml'),
    join('.github', 'workflows', 'ci.yml'),
  ])('%s', (file) => {
    expect(readFileSync(file, 'utf8')).not.toMatch(/VITE_[A-Z_]*SERVICE_ROLE/)
  })
})
